### ISSUE TITLE
Eroare la obtinerea informatiilor de la API

### ISSUE THREAD

**Issue by miclausandrei** [cnecrea/eonromania#1]
Salut,

Mi-am configurat integrarea in HA folosind datele de logare in eon my-line + codul de incasare dar primesc urmatoarea eroare:

Eroare la obținerea datelor din arhivă: Status=400, Răspuns={"code":"3018","description":"Invalid account contract for user","entity":null}
Eroare la obținerea datelor despre index: Status=400, Răspuns={"code":"3018","description":"Invalid account contract for user","entity":null}

Ai idee cum se poate rezolva?

Multumesc

**Comment by cnecrea** [comment]
> Salut,
> 
> Mi-am configurat integrarea in HA folosind datele de logare in eon my-line + codul de incasare dar primesc urmatoarea eroare:
> 
> Eroare la obținerea datelor din arhivă: Status=400, Răspuns={"code":"3018","description":"Invalid account contract for user","entity":null} Eroare la obținerea datelor despre index: Status=400, Răspuns={"code":"3018","description":"Invalid account contract for user","entity":null}
> 
> Ai idee cum se poate rezolva?
> 
> Multumesc


Esti client E-ON sau Delagaz? Erorr code 3018, imi suna Delagaz, gen.

**Comment by gheomg** [comment]
Am incercat si eu integrarea si nu pare sa mearga. Pe langa erorile de mai sus mai am si urmatoarea:
`2024-12-29 12:42:02.876 ERROR (MainThread) [custom_components.eonromania] Eroare la obținerea datelor utilizator: Status=403, Răspuns={"code":"403","description":"You do not have enough rights to perform this operation"}`
Am introdus toate datele corect.
In HA imi apare integrarea, dar singurul entity e "date contract" care are statusul "unknown".
Sunt client E-ON.

**Comment by msuvar** [comment]
Aceleasi probleme si in cazul meu. Primesc urmatoarele erori:
Eroare la obținerea datelor utilizator: Status=403, Răspuns={"code":"403","description":"You do not have enough rights to perform this operation"}
Eroare la obținerea datelor despre index: Status=400, Răspuns={"code":"3018","description":"Invalid account contract for user","entity":null}
In HA imi apare integrarea, dar singurul entity e "date contract" care are statusul "unknown".
Sunt client E-ON.

**Comment by cnecrea** [comment]
> Am incercat si eu integrarea si nu pare sa mearga. Pe langa erorile de mai sus mai am si urmatoarea:
> 
> `2024-12-29 12:42:02.876 ERROR (MainThread) [custom_components.eonromania] Eroare la obținerea datelor utilizator: Status=403, Răspuns={"code":"403","description":"You do not have enough rights to perform this operation"}`
> 
> Am introdus toate datele corect.
> 
> In HA imi apare integrarea, dar singurul entity e "date contract" care are statusul "unknown".
> 
> Sunt client E-ON.


Salut și mulțumesc de feedback!


Știu ca unii clienți care sunt de la Delagaz, au eroarea asta.

Pe de altă parte, știu ca exista dashboardul "vechi" (v1), pentru "un alt tip de clienți" (fără să pot defini în prezent tipul de client)

În ambele cazuri, o să revin cu un fix la integrare, pentru ca ea să facă singură schimbare de API links pentru acești tip de clienți.


Pe mai târziu o vă cer să îmi atașați niște date, pentru a soluționa acest bug.

**Comment by miclausandrei** [comment]
> > Salut,
> > Mi-am configurat integrarea in HA folosind datele de logare in eon my-line + codul de incasare dar primesc urmatoarea eroare:
> > Eroare la obținerea datelor din arhivă: Status=400, Răspuns={"code":"3018","description":"Invalid account contract for user","entity":null} Eroare la obținerea datelor despre index: Status=400, Răspuns={"code":"3018","description":"Invalid account contract for user","entity":null}
> > Ai idee cum se poate rezolva?
> > Multumesc
> 
> Esti client E-ON sau Delagaz? Error code 3018, imi suna Delagaz, gen.
> 
> API links pentru Delagaz sunt diferite, si logarea se face altfel, functie pe care am s-o introduc in viitor (scurt timp).

In eon my line imi apare Operator de Distribuție (OD):DELGAZ GRID S.A. deci posibil sa fiu client delgaz desi contractul a fost facut online pe platforma eon. 


> Am incercat si eu integrarea si nu pare sa mearga. Pe langa erorile de mai sus mai am si urmatoarea: `2024-12-29 12:42:02.876 ERROR (MainThread) [custom_components.eonromania] Eroare la obținerea datelor utilizator: Status=403, Răspuns={"code":"403","description":"You do not have enough rights to perform this operation"}` Am introdus toate datele corect. In HA imi apare integrarea, dar singurul entity e "date contract" care are statusul "unknown". Sunt client E-ON.

Exact aceleasi erori le am si eu in loguri. Deci posibil sa fie acelasi caz.

**Comment by cnecrea** [comment]
E bine de știut ca exista problema asta. Nu e chiar mare lucru, se rezolva in viitorul update. Sper sa fie mâine sau după anul nou.

**Comment by gheomg** [comment]
Acum am verificat si eu mai bine. Si da, si in cazul meu distribuitor este Delgaz Grid SA.
Pot ajuta si eu cu testarea cand va fi disponibil fixul.

**Comment by msuvar** [comment]
Confirm si eu. Tot Delgaz grid este trecut la distribuitor, si in cazul meu.

**Comment by andreisavescu** [comment]
Și eu am același erori

**Comment by clmun** [comment]
Salut
Nici la mine nu merge.
Eu nu am avut erori, dar nu s-au creat senzorii. Doar sensor.date_contract_210209xxxx care este unknown.

Si da, am aflat si eu din factura ca distribuitor e DELGAZ GRID. Dar oare are legatura?

**Comment by andreisavescu** [comment]
Nici eu nu am avut erori la crearea configurării, ci apar in log. Trebuie sa dai din interiorul integrării "enable debug"

**Comment by clau-bucur** [comment]
Asa si la mine. Am incercat pentru 2 coduri de incasare si erorile apar in ambele cazuri: gaz (distribuitor Delgaz) si energie (distribuitor DEER).

**Comment by cnecrea** [comment]
Vă mulțumesc tuturor pentru feedback! 

Am identificat problema. Tot ce vă rog este să aveți puțină răbdare, iar în următorul update veți primi o rezolvare pentru asta. 😊

**Comment by ovydyu1985** [comment]
La mine apare "Date contract     Necunoscut"
Am pus corect datele de la EON

**Comment by cnecrea** [comment]
Am găsit soluția mai repede decât mă așteptam! De fapt, credeam inițial că există o eroare în formularul de login bazat pe “tip client”, dar nu este așa.

Soluția este foarte simplă. Dacă aveți un cod format din 10 cifre, exemplu: 2100023241, trebuie doar să adăugați două zerouri la începutul codului.

Exemplu:
	•	Înainte: 2100023241
	•	După: 002100023241

Această modificare ar trebui să rezolve problema autentificării. Dacă întâmpinați alte dificultăți, nu ezitați să mă anunțați! 😊

**Comment by gheomg** [comment]
> Am găsit soluția mai repede decât mă așteptam! De fapt, credeam inițial că există o eroare în formularul de login bazat pe “tip client”, dar nu este așa.
> 
> Soluția este foarte simplă. Dacă aveți un cod format din 10 cifre, exemplu: 2100023241, trebuie doar să adăugați două zerouri la începutul codului.
> 
> Exemplu: • Înainte: 2100023241 • După: 002100023241
> 
> Această modificare ar trebui să rezolve problema autentificării. Dacă întâmpinați alte dificultăți, nu ezitați să mă anunțați! 😊

Well, this actually works.

Mersi!

**Comment by cnecrea** [comment]
> > Am găsit soluția mai repede decât mă așteptam! De fapt, credeam inițial că există o eroare în formularul de login bazat pe “tip client”, dar nu este așa.
> > Soluția este foarte simplă. Dacă aveți un cod format din 10 cifre, exemplu: 2100023241, trebuie doar să adăugați două zerouri la începutul codului.
> > Exemplu: • Înainte: 2100023241 • După: 002100023241
> > Această modificare ar trebui să rezolve problema autentificării. Dacă întâmpinați alte dificultăți, nu ezitați să mă anunțați! 😊
> 
> Well, this actually works.
> 
> Mersi!

Da, voi implementa o funcție de verificare care să adauge automat două zerouri la început, dacă codul are exact 10 cifre. Astfel, se vor elimina complet orice dubii legate de formatul corect.

Am verificat și eu pe factură, și într-adevăr, codul meu are 10 cifre fără cele două zerouri. Totuși, acestea trebuie incluse pentru a funcționa corect. Implementarea funcției va simplifica procesul și va evita erorile manuale. 😊

**Comment by cnecrea** [comment]
Fix: Am implementat validarea automată pentru cod_incasare, astfel încât, dacă este introdus cu mai puțin de 12 caractere, sistemul completează automat cu două zerouri (00) în față. Această schimbare simplifică procesul de configurare și previne erorile cauzate de formatarea incorectă a codului.

Dacă nu doriți să descărcați din nou integrarea, soluția este să adăugați manual două zerouri la începutul codului. De exemplu, dacă codul este format din 10 cifre (2100023241), cu 00 adăugat în față, rezultatul final va fi 002100023241.

Dacă doriți să beneficiați de noua funcționalitate, urmați acești pași prin HACS:
	1.	În lista de integrări, dați click pe cele trei puncte situate în dreptul integrării.
	2.	Selectați opțiunea Actualizează informațiile pentru a verifica dacă există actualizări disponibile.
	3.	După actualizarea informațiilor, descărcați noua versiune a integrării.
	4.	Reporniți Home Assistant pentru a aplica modificările.

După acești pași, integrarea va face validarea automată a codului de încasare, eliminând necesitatea oricărei modificări manuale. 😊
